### PR TITLE
Add OSX get-task-allow entitlement

### PR DESCRIPTION
**Pull request by keithc-ca**
Issue: AdoptOpenJDK/openjdk-build#1778

### CODE REVIEW

**Review by DanHeidinga — APPROVED** [review]
lgtm

**Comment by DanHeidinga** [comment]
Merging without a build as this will only be tested by the notarization process

**Comment by DanHeidinga** [comment]
@keithc-ca should this be ported to the openj9-0.22.0 branch for the java 15 release as well?

**Comment by keithc-ca** [comment]
@DanHeidinga, see #16 for the 0.22.0 branch.

**Pull request merged**
