### PR TITLE
Merging jdk-15.0.2+7 into the 0.24.0 release branch

### PR DESCRIPTION
**Pull request by pshipton**
This merges from openj9-staging, since there aren't any unwanted commits for the release.

### CODE REVIEW

**Comment by JasonFengJ9** [comment]
I know it passed the PR build. Is it safer to wait it pass abuild before merging into `v0.24.0` release branch?

**Comment by pshipton** [comment]
We need these changes no matter what because they are the 15.0.2 content. I'm going to start a full release test build after this is merged (all platforms, all testing). We can address any problems that are found before the release is finalized.

**Review by JasonFengJ9 — APPROVED** [review]
Sure, that's fair enough. 
~P.S. abuild finished JDK builds all green, testing is still going.~ that was a stale one.

**Comment by pshipton** [comment]
Since we run full testing on the release content, I've been skipping the abuild testing, as it just takes extra time, delaying the release, and is only a subset.

**Pull request merged**
