### PR TITLE
Revert StringConcatFactory.java commits 

### LINKED ISSUE #9771: jdk15 MethodHandle.rebind() stubbed but used
https://ci.eclipse.org/openj9/job/Pipeline-OpenJDK-Acceptance/258/
```
22:55:19  Exception in thread "main" java.lang.InternalError: Compile stub invoked! Apart from deliberate reflective access, this should not happen. Please report this to the project so it can be addressed
22:55:19  	at java.base/java.lang.invoke.OpenJDKCompileStub.OpenJDKCompileStubThrowError(OpenJDKCompileStub.java:38)
22:55:19  	at java.base/java.lang.invoke.MethodHandle.rebind(MethodHandle.java:1479)
22:55:19  	at java.base/java.lang.invoke.StringConcatFactory.simpleConcat(StringConcatFactory.java:657)
22:55:19  	at java.base/java.lang.invoke.StringConcatFactory.generateMHInlineCopy(StringConcatFactory.java:458)
22:55:19  	at java.base/java.lang.invoke.StringConcatFactory.makeConcatWithConstants(StringConcatFactory.java:354)
22:55:19  	at java.base/java.lang.invoke.MethodHandle.invokeBsm(MethodHandle.java:1070)
22:55:19  	at java.base/java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:1200)
22:55:19  	at jdk.jlink/jdk.tools.jlink.internal.Utils.getPathMatcher(Utils.java:97)
22:55:19  	at jdk.jlink/jdk.tools.jmod.JmodTask$PathMatcherConverter.convert(JmodTask.java:1173)
22:55:19  	at jdk.jlink/jdk.tools.jmod.JmodTask$PathMatcherConverter.convert(JmodTask.java:1169)
22:55:19  	at jdk.internal.opt/jdk.internal.joptsimple.internal.Reflection.convertWith(Reflection.java:154)
22:55:19  	at jdk.internal.opt/jdk.internal.joptsimple.AbstractOptionSpec.convertWith(AbstractOptionSpec.java:120)
22:55:19  	at jdk.internal.opt/jdk.internal.joptsimple.ArgumentAcceptingOptionSpec.convert(ArgumentAcceptingOptionSpec.java:308)
22:55:19  	at jdk.internal.opt/jdk.internal.joptsimple.OptionSet.valuesOf(OptionSet.java:253)
22:55:19  	at jdk.jlink/jdk.tools.jmod.JmodTask.handleOptions(JmodTask.java:1397)
22:55:19  	at jdk.jlink/jdk.tools.jmod.JmodTask.run(JmodTask.java:168)
22:55:19  	at jdk.jlink/jdk.tools.jmod.Main.main(Main.java:34)
```

Blocking compilation of jdk15.

### PR DESCRIPTION
**Pull request by babsingh**
- Revert "8246632: StringConcatFactory::makeConcatWithConstants ..."
- Revert "Revert "8246152: Improve String concat bootstrapping"

The above commits are reverted because of the `MethodHandle.rebind` dependency which can't be supported in OpenJ9 until OpenJ9 adopts the OpenJDK MethodHandles. `rebind` returns a `BoundMethodHandle` which is not currently supported in OpenJ9. 

`StringConcatFactory` also introduced a dependency on `MethodHandle.viewAsType`, which is not currently supported in OpenJ9.

Reverting the above two commits will allow us to temporarily build JDK15 with OpenJ9.

Once OpenJ9 adopts the OpenJDK MethodHandles, the above reverts can be undone.

Fixes: https://github.com/eclipse/openj9/issues/9771

Signed-off-by: Babneet Singh <sbabneet@ca.ibm.com>

### CODE REVIEW

**Comment by DanHeidinga** [comment]
@babsingh This makes sense to unblock the rest of the JDK 15 work.  What's needed to remove the WIP from this PR?

**Comment by babsingh** [comment]
@DanHeidinga These changes should work independently, and can be merged. I have removed the WIP.

**Comment by babsingh** [comment]
@DanHeidinga This issue will also persist in https://github.com/ibmruntimes/openj9-openjdk-jdk. Should I port these changes to that branch?

I have also created https://github.com/eclipse/openj9/issues/9895 to track commits which need to be re-included once OpenJ9 supports the OpenJDK MethodHandle(s).

**Comment by babsingh** [comment]
> These changes should work independently, and can be merged. I have removed the WIP.

**Revising my above answer:** Currently, JDK15+ is broken due to missing OpenJ9 dependencies. This PR will need https://github.com/eclipse/openj9/pull/9865 to successfully build JDK15.

**Comment by DanHeidinga** [comment]
@babsingh We'll need the same change for the jdk repo as well, targeting the staging branch

**Comment by babsingh** [comment]
> We'll need the same change for the jdk repo as well, targeting the staging branch

Created https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/213 to target the jdk repo's staging branch.

I also changed the target branch for the jdk15 repo to openj9-staging. Is this fine? or Should this PR target the openj9 branch?

**Comment by pshipton** [comment]
This one can target the openj9 branch, since the openjdk change has already been merged into this branch. openj9-staging will pick it up from openj9 afterwards.

**Comment by babsingh** [comment]
Changed the target branch to openj9.

**Comment by pshipton** [comment]
This change has conflicts with openj9-staging now. See also https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/213#issuecomment-646809500

It's worth creating the reverts for the openj9-staging branch in another PR, and checking if any new problems are introduced which aren't already fixed via #9865. If the latest can still work with the appropriate reverts, we can move directly to that when merging #9865.

**Comment by babsingh** [comment]
There is a new commit to `StringConcatFactory.java` which is causing the conflict. If we take the revert approach, then any new JDK changes to `StringConcatFactory.java` will cause such a conflict. A framework to temporarily ignore new JDK changes for `StringConcatFactory.java` and keep it in its current state will be helpful to avoid an ongoing effort to fix merge conflicts. Not sure if such a feature exists. @pshipton If you are aware of any alternatives, I will be happy to employ them.

**Comment by babsingh** [comment]
Locally, JDK15+ built fine with https://github.com/eclipse/openj9/pull/9865 and after reverting the latest `StringConcatFactory.java` commit. So, no new OpenJ9 changes are needed.

**Comment by babsingh** [comment]
I would need a confirmation if we are taking the manual revert approach. After receiving the confirmation, I will create/update this PR with the revert of the latest `StringConcatFactory.java` commit.

**Comment by pshipton** [comment]
The alternative is to find some smaller patch we can apply so MethodHandle.rebind() is not used, without reverting each related OpenJDK change. To be effective, the smaller patch needs to have less chance of a merge conflict. Changes to Java 15 are winding down, it's hard to say if the latest StringConcatFactory change is going to be the last.

**Comment by babsingh** [comment]
> The alternative is to find some smaller patch 

Here is a smaller patch: https://github.com/ibmruntimes/openj9-openjdk-jdk15/pull/4. Added an implementation of MethodHandle.viewAsType in https://github.com/eclipse/openj9/pull/9865. jdk-15+28 built fine.

**Pull request closed without merging**
