### PR TITLE
Update CMake Windows support

### PR DESCRIPTION
**Pull request by dnakamura**
- Create new fixpath2.sh tool, which can handle /cygrive/ in the middle
of a path

- Enable using clang to compile the interpreter

Signed-off-by: Devin Nakamura <devinn@ca.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
More important than adding this to the jdk15 repo is to add the changes to https://github.com/ibmruntimes/openj9-openjdk-jdk

Does this fix https://github.com/eclipse/openj9/issues/11300 ?

jenkins compile win,wincm jdk15

**Comment by pshipton** [comment]
```
18:46:05  /cygdrive/f/Users/jenkins/workspace/Build_JDK15_x86-64_windows_Personal/build/.configure-support/generated-configure.sh: line 21114: syntax error near unexpected token `OPENJ9_CLANG,'
18:46:05  /cygdrive/f/Users/jenkins/workspace/Build_JDK15_x86-64_windows_Personal/build/.configure-support/generated-configure.sh: line 21114: `     BASIC_REQUIRE_PROGS(OPENJ9_CLANG, clang)'
```

**Comment by AdamBrousseau** [comment]
@pshipton can this be closed so I can archive this repo?

**Comment by pshipton** [comment]
Closed it.

**Pull request closed without merging**
