### PR TITLE
Fix makefiles for jdk.jcmd

### PR DESCRIPTION
**Pull request by keithc-ca**
* fix regression in ModuleWrapper.gmk which occurred in:
  - 8244044: Refactor phase makefiles to be structured per module
  (include path was over-qualified)

* note: also fixes regression of suppressing unwanted man pages jcmd.1 jinfo.1 jps.1 jstack.1 jstat.1

* remove trailing whitespace in OpenJ9 additions
* remove unnecessary file jdk.jfr/Copy.gmk
* revert addition of customization post hook in jdk.jcmd/Launcher.gmk
* remove files no longer used
* remove openj9-jdk.jcmd-launchers target
* override Launcher.gmk for jdk.jcmd

### CODE REVIEW

**Comment by keithc-ca** [comment]
The copyright check failure for `make/modules/jdk.jcmd/Launcher.gmk` is expected: all changes to that file have been reverted.

**Review by andrew-m-leonard — APPROVED** [review]

**Comment by andrew-m-leonard** [comment]
Copyright check error for make/modules/jdk.jcmd/Launcher.gmk is fine, as the change reverts to exact OpenJDK file now.

**Comment by pshipton** [comment]
@keithc-ca I expect this change needs to be delivered to the openj9-0.22.0 branch as well. To bring this branch up to date, #20 and #22 should also be ported.

**Comment by keithc-ca** [comment]
I think 'need' overstates it, but I'll put a pull request together.

**Comment by keithc-ca** [comment]
@pshipton See #25.

**Pull request merged**
