### PR TITLE
Add vm.bits property

### PR DESCRIPTION
**Pull request by sophia-guo**
Add vm.bits property

Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins test sanity.openjdk all jdk15

**Comment by pshipton** [comment]
The zlinux failure in GCDuringIteration is a known problem.

**Comment by sophia-guo** [comment]
@pshipton updated. Thanks.

**Review by pshipton — APPROVED** [review]

**Comment by pshipton** [comment]
jenkins test sanity.openjdk plinux,aix,osx,win jdk11

**Comment by pshipton** [comment]
The test failures are expected.

**Pull request merged**
